# Generated by Django 5.1.5 on 2025-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classique - Bleu'), ('modern', 'Moderne - Violet'), ('elegant', 'Élégant - Vert'), ('creative', 'Créatif - Orange'), ('professional', 'Professionnel - Gris')], default='classic', max_length=20),
        ),
    ]
